ROOT=../../..


configure:
	python3 $(ROOT)/app/nmcmake.py configure 

build:
	python $(ROOT)/app/nmcmake.py make 
	
kill:
	python3 $(ROOT)/app/nmcmake.py kill
	
run :
	python3 $(ROOT)/app/nmcmake.py make run

clean :
	python3 $(ROOT)/app/nmcmake.py make clean
