INC_DIRS         = -I../../include -I$(NEURO)/include

SRC_DIRS = $(ROOT)/src/nmpls/Metric
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/FFT0032/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/IFFT0032/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/FFT0064/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/IFFT0064/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/FFT0128/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/IFFT0128/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/FFT0256/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/IFFT0256/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/FFT0512/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/IFFT0512/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/FFT1024/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/IFFT1024/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/FFT2048/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/IFFT2048/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/FFT4096/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/IFFT4096/nm
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/common
SRC_DIRS+= $(ROOT)/src/nmpls/FFT_32fcr/FFTFree/common
SRC_DIRS+= $(ROOT)/src/nmplv/Support/nm
SRC_DIRS+= $(ROOT)/src/nmplv/Support/common
SRC_DIRS+= $(ROOT)/src/nmplv/Stat/nmf
SRC_DIRS+= $(ROOT)/src/nmplv/Select/nmf
SRC_DIRS+= $(ROOT)/src/nmplv/Stat/common
SRC_DIRS+= $(ROOT)/src/nmplv/Stat/nm
SRC_DIRS+= $(ROOT)/src/nmplv/Arithmetics/common
SRC_DIRS+= $(ROOT)/src/nmplv/Arithmetics/nmf
SRC_DIRS+= $(ROOT)/src/nmplv/Init/common
SRC_DIRS+= $(ROOT)/src/nmplv/Init/nmf
SRC_DIRS+= $(ROOT)/src/nmplv/Init/nm-risc
SRC_DIRS+= $(ROOT)/src/nmblas/level1/nm
SRC_DIRS+= $(ROOT)/src/nmblas/level1/nmcore
SRC_DIRS+= $(ROOT)/src/nmblas/level2/nm
SRC_DIRS+= $(ROOT)/src/nmblas/level2/nmcore
SRC_DIRS+= $(ROOT)/src/nmplm/Init/nmf
